// ignore_for_file: constant_identifier_names, file_names

class Constants {
  static const String VOWELS = "aıoöuüei";
  static const String FRONT_VOWELS = "aıou";
  static const String BACK_VOWELS = "eiöü";
  static const String HARD_CONSONANTS = "fstkçşhp";
  static const String DISCONTINIOUS_HARD_CONSONANTS = "pçtk";
  static const String SOFTEN_DHC = "bcdğ";
  static const String DISCONTINIOUS_HARD_CONSONANTS_AFTER_SUFFIX = "pçk";
  static const String SOFTEN_DHC_AFTER_SUFFIX = "bcğ";

  static const Map<String, String> MINOR_HARMONY = {
    'a': 'ı',
    'e': 'i',
    'ö': 'ü',
    'o': 'u',
    'ı': 'ı',
    'i': 'i',
    'u': 'u',
    'ü': 'ü'
  };

  static const Map<String, String> HARMONY_FOR_PRESENT_FIRST = {
    'a': 'a',
    'e': 'e',
    'ö': 'e',
    'o': 'a',
    'ı': 'a',
    'i': 'e',
    'u': 'a',
    'ü': 'e'
  };

  static const Map<String, String> HARMONY_FOR_PRESENT = {
    'e': 'i',
    'i': 'e',
    'ö': 'ü',
    'ü': 'ü',
    'a': 'ı',
    'u': 'u',
    'o': 'ı',
    'ı': 'a',
  };

  static const List<String> EXCEPTIONS = [
    "ahval",
    "akropol",
    "alkol",
    "antisosyal",
    "ametal",
    "amiral",
    "ampul",
    "anormal",
    "bandrol",
    "bemol",
    "beşamol",
    "bilkat",
    "cemaat",
    "cemal",
    "deccal",
    "dikkat",
    "ekol",
    "ekümenapol",
    "emsal",
    "enstrümental",
    "enterasyonal",
    "faal",
    "faul",
    "final",
    "general",
    "glikol",
    "gol",
    "hakikat",
    "hal",
    "harf",
    "hayal",
    "hilal",
    "hiperbol",
    "hol",
    "integral",
    "iştigal",
    "istikbal",
    "istiklal",
    "jurnal",
    "kabul",
    "kalp",
    "kanaat",
    "kapital",
    "karambol",
    "katedral",
    "kefal",
    "kemal",
    "kıraat",
    "kolestrol",
    "kontrol",
    "koramiral",
    "korgeneral",
    "legal",
    "liberal",
    "liyakat",
    "lokal",
    "mahmul",
    "mamul",
    "mahsul",
    "maktul",
    "makbul",
    "makul",
    "mareşal",
    "meal",
    "menkul",
    "mentol",
    "meral",
    "meşakkat",
    "meşgul",
    "metal",
    "materyal",
    "metropol",
    "mineral",
    "misal",
    "moral",
    "müzikal",
    "müzikhol",
    "nasyonal",
    "normal",
    "ohal",
    "oramiral",
    "orgeneral",
    "orijinal",
    "oryantal",
    "oval",
    "parabol",
    "paranormal",
    "pastoral",
    "perhidrol",
    "petrol",
    "radikal",
    "refakat",
    "resital",
    "resul",
    "rol",
    "saat",
    "sadakat",
    "santral",
    "sansasyonal",
    "şefkat",
    "şevval",
    "sinyal",
    "sosyal",
    "spesiyal",
    "sual",
    "tefal",
    "termal",
    "terminal",
    "total",
    "trambol",
    "tropikal",
    "tuğamiral",
    "tuğgeneral",
    "tümamiral",
    "tümgeneral",
    "turnusol",
    "tuval",
    "usul",
    "zeval",
    "ziraat"
  ];
}
